alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias ls="ls -F --color=auto"
alias la="ls -a"
alias ll="ls -l"
alias grep="grep --color"
alias cl="clear"
alias logs="~/scripts/colorizer.pl --config ~/scripts/logs.conf"
alias mylogs="color --config ~/dotfiles/custom_logs.conf"
alias color="~/dotfiles/colorizer.pl"
alias watcher="~/scripts/filewatcher.pl"
alias mygrep="color --config ~/scripts/mygrep.conf"
alias tmux="tmux -2 -u"
alias gotmux="~/gotmux.sh"
alias gus="git status"
alias sun="sort | uniq"
alias sunc="sort | uniq -c"
alias 3mon="/home/okoshovets/.screenlayout/3mon.sh"
alias 2mon="xrandr --output DP-2-2 --above eDP-1 --mode 1920x1080 --output DP-2-1 --off"
alias 1mon="xrandr --output eDP-1 --mode 1920x1080 --output DP-2-1 --off --output DP-2-2 --off"
alias devchrome="chromium-browser --disable-web-security --ignore-certificate-errors --user-data-dir='/tmp/chromedev'"
alias nless="/usr/local/share/nvim/runtime/macros/less.sh"
