alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias ls="ls -F --color=auto"
alias la="ls -a"
alias ll="ls -l"
alias grep="grep --color"
alias cl="clear"
alias home="cd $HOME"
alias logs="~/scripts/colorizer.pl --config ~/scripts/logs.conf"
alias mylogs="color --config ~/scripts/custom_logs.conf"
alias color="~/scripts/colorizer.pl"
alias watcher="~/scripts/filewatcher.pl"
alias mygrep="color --config ~/scripts/mygrep.conf"
alias tmux="tmux -2 -u"
alias gotmux="~/gotmux.sh"
