#!/bin/bash

ROOT_UID=0
install_list="
	adobe-flashplugin
	audacity
	build-essential
	cmake
	g++
	gcc
	git
	nmon
	opera-stable
	perl
	pinta
	playonlinux
	qbittorrent
	steam
	sublime-text
	virtualbox-qt
	vim
	vlc
	wine1.8
	winetricks
"
libs_list="
g++-multilib
gcc-multilib
libasound2-dev:i386
libfreetype6-dev:i386
libglu1-mesa:i386
libgnutls28-dev:i386
libgsm1-dev:i386
libgtk2.0-0:i386
libjpeg8-dev:i386
liblcms2-dev:i386
libldap2-dev:i386
libmpg123-dev:i386
libopenal-dev:i386
libopenal1:i386
libsdl-image1.2:i386
libsdl-ttf2.0-0:i386
libv4l-dev:i386
libx11-dev:i386
libxinerama-dev:i386
libxml2-dev:i386
libxrender-dev:i386
libxrender1-dbg:i386
libxslt1-dbg:i386
libxslt1-dev:i386
zlib1g-dev:i386
"

vimrc="
	set nu \n\
set tabstop=4 \n\
set autoindent
"

if [ $UID -ne $ROOT_UID ]
then
	echo "Root rights needed"
else
	add-apt-repository ppa:ubuntu-wine/ppa
	add-apt-repository ppa:qbittorrent-team/qbittorrent-stable
	add-apt-repository "deb http://deb.opera.com/opera/ stable non-free"
	wget -O - http://deb.opera.com/archive.key | sudo apt-key add -
	apt-get update
	apt-get install $install_list
	apt-get install $libs_list
	apt-get upgrade
	echo -e $vimrc > .vimrc
fi
